print_info() {
    info os
    info host
    info kernel
    info uptime
    info packages
    info shell
    info de
    info wm
    info terminal
    info cpu
    info gpu
    info memory
    info cols
}

ascii_distro="off"
image_backend="ascii"
image_source="/etc/neofetch/tortuga.txt"
image_size="auto"