name: Build TortugaLinux
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up QEMU and Buildah/Podman
        uses: docker/setup-qemu-action@v3

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push TortugaLinux Max
        run: |
          IMAGE_PATH=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          podman build -f Containerfile.max -t $IMAGE_PATH:max .
          podman push $IMAGE_PATH:max

      - name: Build and Push TortugaLinux Min
        run: |
          IMAGE_PATH=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          podman build -f Containerfile.min -t $IMAGE_PATH:min .
          podman push $IMAGE_PATH:min

      - name: Build and Push TortugaLinux Installer
        run: |
          IMAGE_PATH=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          podman build -f installer/Containerfile -t $IMAGE_PATH:installer .
          podman push $IMAGE_PATH:installer